"""红色运动目标系统的现场可调参数。"""

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
CAMERA_FPS = 30
CAMERA_BUFFER_COUNT = 1
RECT_DETECTION_WIDTH = 320
RECT_DETECTION_HEIGHT = 240
RECT_DETECT_INTERVAL_FRAMES = 2
DISPLAY_INTERVAL_FRAMES = 2

RECT_THRESHOLD = 10000
RECT_STABLE_FRAMES = 3
PAIR_MISS_FRAMES = 15
MAX_CORNER_JITTER = 5
MIN_RECT_AREA_RATIO = 0.05
MAX_RECT_AREA_CHANGE_RATIO = 0.10
A4_ASPECT_RATIO = 1.414
A4_ASPECT_TOLERANCE = 0.25
SCREEN_ASPECT_RATIO = 1.0
SCREEN_ASPECT_TOLERANCE = 0.20
SCREEN_PAIR_MISS_FRAMES = 1
SCREEN_EXPECTED_AREA_RATIO = 0.52
MIN_INNER_OUTER_AREA_RATIO = 0.50
RECT_ROI_MARGIN = 24

RED_LAB_THRESHOLDS = [[0, 80, 40, 80, 10, 80]]
LASER_MIN_PIXELS = 2
LASER_MAX_PIXELS = 500
LASER_MAX_JUMP_PX = 100
LASER_MIN_ROUNDNESS = 0.0

EDGE_SEGMENTS = 5
ARRIVE_RADIUS = 8
STABLE_FRAMES = 3
WAYPOINT_SEND_INTERVAL_MS = 100
TOUCH_DEBOUNCE_MS = 150
MODE_BUTTON_TOP = 40
MODE_BUTTON_HEIGHT = 50
RUNTIME_BUTTON_HEIGHT = 60

UART_TX_PIN = "A19"
UART_RX_PIN = "A18"
UART_TX_FUNCTION = "UART1_TX"
UART_RX_FUNCTION = "UART1_RX"
UART_DEVICE = "/dev/ttyS1"
UART_BAUDRATE = 115200
